### ISSUE TITLE
Why not include the following symbols

### ISSUE THREAD

**Issue by ouboub** [Christoph-D/latex-unicode-math-mode#2]
hi

why not include
("\\sqrt"  ?\u221A)
("\\Lightning"  ?\u26A1)
("\\lightning"  ?\u26A1)
    

regards

Uwe Brauer

**Comment by Christoph-D** [comment]
The lightning symbol should be fine. The root symbol is special and doesn't work well with Unicode. Its optional argument breaks if the symbol is replaced with a unicode character: `√[3]{2}` doesn't produce the correct output.

I stopped using Emacs and Latex some years ago, so I'm no longer familiar enough with them to find a workaround for `\sqrt`. But I'll add the lightning symbol.

**Comment by ouboub** [comment]
> The lightning symbol should be fine. The root symbol is special and doesn't work well with Unicode. Its optional argument breaks if the symbol is replaced with a unicode character: `√[3]{2}` doesn't produce the correct output.
> 
> I stopped using Emacs and Latex some years ago, so I'm no longer familiar enough with them to find a workaround for `\sqrt`. But I'll add the lightning symbol.

I see, I come up with some other symbols I do miss
```
	      ("\\pm"   ?\u00B1)
	      ("\\|"   ?\u2016)
	      ("\\varkappa"   ?\u03F0)
              ("\\mathbullet"   ?•)
              ("\\smiley"   ?🙂)
              ("\\frownie"   ?☹)
	      ("\\varrho"   ?ϱ)))
```
I can add them locally via custom, but if you still commit and push, that would be nice, as well
